
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Bio from '../components/bio'
import Skills from '../components/skills'
import Footer from '../components/footer'
import Experience from '../components/experience'

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Shane Woods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Encode+Sans:wght@300&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css" />
      </Head>
      <Navbar />
      <Bio />
      <Skills />
      <Experience />
      <Footer />
    </div>
  )
}
