import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import HomeBio from '../components/homebio'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <HomeBio />
      <Footer />
    </div>
  )
}
